src/components/GitterRoomsList/index.js

This PR resolves #99 
Added the correct prop-types and null-check to the component GitterRoomList.
Handle empty title prop 
Add correct PropTypes

update proptype and null-check in GitterRoomList component

---

README.md

This PR updates the readme guidelines for setting up and contributing to the project

Update the Readme Guidelines

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR adds the required templates for issues, bugs and feature reports and pull requests to be opened

add templates for issues and PR

---

src/components/ButtonWithHeading/ButtonWithHeading.md
src/components/Contact/Contact.md

We have planned to use Storybook for documentation. Thus, just for the time being, we can add a temporary markdown file to give information about how to use that components with props
Improve documentation for current components

add markdown for initial components

---

index.js
src/components/ButtonWithHeading/ButtonWithHeading.md
src/components/ButtonWithHeading/index.js
src/components/ButtonWithHeading/style.sass
src/components/GitterRoomsList/GitterRoomItem.js
src/components/GitterRoomsList/GitterRoomList.md
src/components/GitterRoomsList/index.js
src/components/GsocIdeaList/GsocIdeaList.md
src/components/GsocIdeaList/index.js
src/components/GsocIdeaList/style.sass
src/components/GuideLines/GuideLines.md
src/components/GuideLines/index.js
src/components/Header/Header.md
src/components/Header/index.js
src/components/ImageAvatar/ImageAvatar.md
src/components/ImageAvatar/index.js
src/components/ImageAvatar/style.sass
src/components/ImageGrid/ImageGrid.md
src/components/ImageGrid/index.js
src/components/MailingListFeed/MailingListFeedItem.js
src/components/MailingListFeed/style.sass
src/components/SearchBar/SearchBar.md
src/components/SearchBar/index.js
src/components/SearchBar/style.sass
src/components/Team/Team.md
src/components/Team/index.js
src/components/Team/style.sass

This PR makes the existing ImageGrid component more reusable via props and also passing texts, created a new reusable ImageAvatar component, add previous projects featured on the IdeaList component and update the GitterRoomList to show all the rooms for an organization, improves the button component to set the width of button using props, create a reusable search bar and add the search functionality to the team list component, improves the guidelines component to also have an optional image field.
Improving the existing components functionally and adding search functionality
The gitter-room-list is updated to show all the rooms
Added the previous projects on idealist
created new image-avatar component
Made the image-grid component more reusable
Create a new reusable search bar component …

Improve ImageGrid, ImageAvatar, Previous Projects and GitterRoom, Guidelines, Mailing-list and create a search bar component

---

src/components/Contact/index.js
src/components/JobOpenings/JobOpenings.md
src/components/JobOpenings/index.js
src/components/MailingListFeed/MailingListFeed.md
src/components/MediumFeed/FeedItem.js
src/components/MediumFeed/MediumFeed.md
src/components/MediumFeed/index.js
src/components/MediumFeed/style.sass
src/components/ProjectDetail/ProjectDetail.md
src/components/ProjectDetail/index.js
src/components/ProjectsList/ProjectsList.md
src/components/ProjectsList/index.js
src/components/ProjectsList/style.sass
src/components/SearchBar/SearchBar.md
src/components/SearchBar/index.js
src/components/Team/index.js

This PR improves the contact, job openings, medium-feed, project details, and other components functionally and makes them more reusable. Also added the search functionality to the ProjectList component.
Improving the current components functionally and reusability
Added the search function to the project-list component
Improved the project detail component to render only the things passed as props
Improve the opportunities component to show all openings and link to apply
Made the medium feed reusable and customized via props for all screen widths

Improve the Contact, Job Openings, MediumFeed, ProjectDetails Components, add the search functionality to ProjectList

---

src/components/About/About.md
src/components/About/index.js
src/components/About/style.sass
src/components/Card/Card.md
src/components/Card/index.js
src/components/Card/style.sass
src/components/Carousel/Carousel.md
src/components/Carousel/index.js
src/components/Carousel/style.sass
src/components/ComingSoon/ComingSoon.md
src/components/ComingSoon/index.js
src/components/ComingSoon/style.sass
src/components/PageNotFound/PageNotFound.md
src/components/Pricing/ItemPrice.js
src/components/Pricing/Pricing.md
src/components/Pricing/index.js
src/components/Pricing/style.sass
src/components/Spinners/Spinners.md
src/components/Spinners/index.js
src/components/Team/Team.md
src/components/Team/index.js
src/components/Team/style.sass
src/components/Timeline/Timeline.md
src/components/Timeline/index.js
src/components/Timeline/style.sass
src/components/Timestamp/Timestamp.md
src/components/Timestamp/index.js
src/components/Timestamp/style.sass

Created many new reusable components like - carousel, pricing, timeline, timestamp, countdown, card, spinner, about-us components and improved the team component to also show details of the team-person
creating newer components will increase the range of the project
**<p align="center">Created the Reusable Carousel Component</p>**
**<p align="center">Created the Reusable Timeline Component</p>**
**<p align="center">Created the Reusable Pricing Component</p>**
**<p align="center">Created the Reusable Timestamp Component</p>**
**<p align="center">Created the Reusable Card Component</p>**
**<p align="center">Created the Reusable Countdown Component</p>**
**<p align="center">Added the show details of team-member function in the Team Component</p>**
**<p align="center">Created the Reusable …

Create Carousel, Pricing, Timeline, Timestamp, Countdown, Card and other new components

---

CONTRIBUTING.md

This PR resolves #128
Created a contributing.md file for contributors.

Added CONTRIBUTION.md 

---

src/components/InfoComponent/InfoComponent.stories.js
src/components/InfoComponent/index.js
src/components/InfoComponent/infoComponent.md
src/components/InfoComponent/style.sass

Added (Mid Section) InfoComponent for the first theme
Resolves #227

Added (Mid Section) InfoComponent for the first theme

---

src/components/ClickableCard/ClickableCard.md
src/components/ClickableCard/ClickableCard.stories.js
src/components/ClickableCard/index.js
src/components/ClickableCard/styles.js

Implement a clickable card component. So that user can see details in the card and navigate to the relevant page.
* Implement new clickable card component
* When user hover the image, image will be zoomed in
* Create story for component
* Add documentation
- npm i
- npm run storybook (story will be displayed in General/ClickableCard )
Resolves https://github.com/scorelab/Webiu/issues/229

Implement Clickable Card Component

---

src/components/InfoCompWithList/InfoCompWithList.stories.js
src/components/InfoCompWithList/index.js
src/components/InfoCompWithList/infoCompWithList.md
src/components/InfoCompWithList/style.sass

Added (Mid Section 2) InfoComponentWithList for the first theme
Resolves #231 
2. Mobile View

Added (Mid Section 2) InfoComponentWithList for the first theme

---

src/components/DisplayFeature/DisplayFeature.md
src/components/DisplayFeature/DisplayFeature.stories.js
src/components/DisplayFeature/index.js
src/components/DisplayFeature/style.sass

Added (Mid Section 3) DisplayFeature Component for the first theme
Resolves #235
2. Mobile View

Added (Mid Section 3) DisplayFeature Component for the first theme

---

src/components/CartTile/CartTile.md
src/components/CartTile/CartTile.stories.js
src/components/CartTile/index.js
src/components/CartTile/styles.js

Implement a CartTile component. So that user can view items in the user cart and add items, remove items, delete all items from the cart.
* Implement CartTile component
* Implement story for this component
* Create document for this component
- npm i
- npm run storybook (story will be displayed in E-Commerce/CartTile )
Resolves https://github.com/scorelab/Webiu/issues/238

Implement CartTile component 

---

src/components/IndividualCard/IndividualCard.md
src/components/IndividualCard/IndividualCard.stories.js
src/components/IndividualCard/index.js
src/components/IndividualCard/style.sass

Added Individual Card Component for the first theme
Resolves #237

Added Individual Card Component for the first theme

---

src/components/SignIn/SignIn.md
src/components/SignIn/SignIn.stories.js
src/components/SignIn/index.js
src/components/SignIn/styles.js
src/components/SignIn/validate.js

Implement a SignIn component in the first theme. So that user can enter the email & password and sign in to the web site.
* Implement Sign In component
* Add validation logic
* Show error messages
* Create story for the component
* npm i
* npm run storybook (story will be displayed in E-Commerce/SignIn )
Resolves https://github.com/scorelab/Webiu/issues/242

Implement SignIn Component With Validation

---

src/components/OrderSummery/OrderSummery.md
src/components/OrderSummery/OrderSummery.stories.js
src/components/OrderSummery/index.js
src/components/OrderSummery/styles.js

Implement a Order Summery component in the first theme. So that user can see the order summery.
* Implement OrderSummery Component
* Implement Story for the component
* npm i
* npm run storybook (story will be displayed in E-Commerce/OrderSummery )
Resolves https://github.com/scorelab/Webiu/issues/244

Implement Order Summery Component

---

src/components/ShipmentDetail/ShipmentDetail.md
src/components/ShipmentDetail/ShipmentDetail.stories.js
src/components/ShipmentDetail/index.js
src/components/ShipmentDetail/styles.js

Implement a Shipment Detail Component in the first theme. So that user can input their details and proceed the payment.
* Implement ShipmentDetail Component
* Implement Story for the component
* npm i
* npm run storybook (story will be displayed in E-Commerce/ShipmentDetail )
Resolves https://github.com/scorelab/Webiu/issues/246

Implement Shipment Detail Component

---

src/components/NavBarThemeOne/NavBarThemeOne.md
src/components/NavBarThemeOne/NavBarThemeOne.stories.js
src/components/NavBarThemeOne/index.js
src/components/NavBarThemeOne/style.sass

Added NavBar component for the first theme
Resolves https://github.com/scorelab/Webiu/issues/219
1.  Desktop 
2. Mobile

Added NavBar component for the first theme

---

src/components/IndividualCardGrid/IndividualCardGrid.md
src/components/IndividualCardGrid/IndividualCardGrid.stories.js
src/components/IndividualCardGrid/index.js
src/components/IndividualCardGrid/style.sass

Added Individual Card  Grid Component for the first theme
Resolves #237

Added IndividualCardGrid component for the first theme

---

src/components/NavBarThemeTwo/NavBarThemeTwo.md
src/components/NavBarThemeTwo/NavBarThemeTwo.stories.js
src/components/NavBarThemeTwo/index.js
src/components/NavBarThemeTwo/style.sass

Added NavBar component for the Second theme
Resolves https://github.com/scorelab/Webiu/issues/253
1.  Desktop 
2. Mobile

Added NavBar Component for the Second Theme

---

src/components/HeroSectionThemeTwo/HeroSectionThemeTwo.md
src/components/HeroSectionThemeTwo/HeroSectionThemeTwo.stories.js
src/components/HeroSectionThemeTwo/index.js
src/components/HeroSectionThemeTwo/style.sass

Added Hero Section component for the Second Theme 
Resolves #255

Added Hero Section Component for the Second Theme

---

.gitignore
src/components/ScrollToTopButton/ScrollToTopBehaviour.js
src/components/ScrollToTopButton/ScrollToTopButton.md
src/components/ScrollToTopButton/ScrollToTopButton.stories.js
src/components/ScrollToTopButton/index.js
src/components/ScrollToTopButton/styles.js

Implement a ScrollToTop Button Component in the second theme. So that user can scroll the page to top easily once they are down in the page.
* Implement ScrollToTop button component
* Implement the functionality
* npm i
* npm run storybook (story will be displayed in CustomerService/ScrollToTopButton )
Resolves https://github.com/scorelab/Webiu/issues/258

Implement ScrollToTop button component

---

src/components/StyledSelect/StyledSelect.md
src/components/StyledSelect/StyledSelect.stories.js
src/components/StyledSelect/index.js
src/components/StyledSelect/styles.js

Implement a Select component with more styles in the second theme. So that user can select his/her preference from the drop down list.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=0%3A2
* Implement StyledSelect component
* npm i
* npm run storybook (story will be displayed in CustomerService/StyledSelect )
Resolves https://github.com/scorelab/Webiu/issues/262

Implement StyledSelect component

---

src/components/FooterThemeTwo/FooterThemeTwo.md
src/components/FooterThemeTwo/FooterThemeTwo.stories.js
src/components/FooterThemeTwo/index.js
src/components/FooterThemeTwo/style.sass

Added Footer Component for the Second Theme
Resolves #261
Desktop  View
Mobile  View

Added Footer Component for the Second Theme

---

src/components/Collaborations/Collaborations.md
src/components/Collaborations/Collaborations.stories.js
src/components/Collaborations/index.js
src/components/Collaborations/style.sass

Added Collaborations Component for the Second Theme
Resolves #263 
Desktop  View
Mobile  View

Added Collaborations Component for the Second Theme

---

src/components/ServicesCard/ServicesCard.md
src/components/ServicesCard/ServicesCard.stories.js
src/components/ServicesCard/index.js
src/components/ServicesCard/style.sass

Added services Card Component for the first theme
Resolves #257 

Added ServicesCard Component for the Second Theme

---

src/components/IndividualCard/IndividualCard.md
src/components/IndividualCardGrid/IndividualCardGrid.md
src/components/ServicesCardGrid/ServicesCardGrid.md
src/components/ServicesCardGrid/ServicesCardGrid.stories.js
src/components/ServicesCardGrid/index.js
src/components/ServicesCardGrid/style.sass

Added ServicesCardGrid Component for the Second Theme
Resolves #257 

Added ServicesCardGrid Component for the Second Theme

---

src/components/StyledTextField/StyledTextField.md
src/components/StyledTextField/StyledTextField.stories.js
src/components/StyledTextField/index.js
src/components/StyledTextField/styles.js

Implement a TextField component with more styles in the second theme. So that user can enter his/her details in the text field.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=0%3A2
* Implement StyledSelect component
* npm i
* npm run storybook (story will be displayed in CustomerService/StyledTextField )
Resolves https://github.com/scorelab/Webiu/issues/267

Implement TextField component

---

src/components/DetailCard/DetailCard.md
src/components/DetailCard/DetailCard.stories.js
src/components/DetailCard/index.js
src/components/DetailCard/style.sass
src/components/IndividualCard/index.js
src/components/IndividualCard/style.sass

Added Detail Card Component for the Second Theme
Resolves #271  

Added Detail Card Component for the Second Theme

---

src/components/DetailCardGrid/DetailCardGrid.md
src/components/DetailCardGrid/DetailCardGrid.stories.js
src/components/DetailCardGrid/index.js
src/components/DetailCardGrid/style.sass

Added DetailCardGrid Component for the Second Theme 
Resolves #271  

Added DetailCardGrid Component for the Second Theme

---

src/components/Reviews/Reviews.md
src/components/Reviews/Reviews.stories.js
src/components/Reviews/index.js
src/components/Reviews/styles.js

Implement a reviews section in the second theme. So that user users can see the past reviews about the person.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=0%3A2
* Implement reviews section component
* npm i
* npm run storybook (story will be displayed in CustomerService/Reviews )
Resolves https://github.com/scorelab/Webiu/issues/278

Implement Reviews Section

---

src/components/ContactUs/ContactUs.md
src/components/ContactUs/ContactUs.stories.js
src/components/ContactUs/index.js
src/components/ContactUs/style.sass

Added Contact Us Component for the Second Theme
Resolves #273

Added "Contact Us" Component for the Second Theme

---

src/components/IndividualCard/index.js
src/components/IndividualCard/style.sass
src/components/NewsFeed/NewsFeed.md
src/components/NewsFeed/NewsFeed.stories.js
src/components/NewsFeed/index.js
src/components/NewsFeed/style.sass

Added NewsFeed Component for the First Theme
Resolves #241 
1.  Desktop

Added NewsFeed Component for the First Theme

---

src/components/FeatureCard/FeatureCard.md
src/components/FeatureCard/FeatureCard.stories.js
src/components/FeatureCard/index.js
src/components/FeatureCard/style.sass

Added Our FeatureCard Component for the Second Theme
Resolves #281

Added Our FeatureCard Component for the Second Theme

---

src/components/OurMission/Mission.md
src/components/OurMission/Mission.stories.js
src/components/OurMission/index.js
src/components/OurMission/style.sass

Added "Our Mission" Component for the Second Theme
Resolves #272

Added "Our Mission" Component for the Second Theme

---

src/components/WhyChooseUs/WhyChooseUs.md
src/components/WhyChooseUs/WhyChooseUs.stories.js
src/components/WhyChooseUs/index.js
src/components/WhyChooseUs/style.sass

Added the "WhyChooseUs" Component for the Second Theme
Resolves #284 

Added "WhyChooseUs" Component for the Second Theme

---

src/components/StatisticsSection/StatisticsSection.md
src/components/StatisticsSection/StatisticsSection.stories.js
src/components/StatisticsSection/index.js
src/components/StatisticsSection/styles.js
src/styles/theme.js

Implement a statistics section in the third theme. So that user can see the statistics about an institute or organization.
* Implement statistics section component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/StatisticsSection )
Resolves https://github.com/scorelab/Webiu/issues/297

Implement Statistics Section Component

---

src/components/SearchBarComponent/SearchBarComponent.md
src/components/SearchBarComponent/SearchBarComponent.stories.js
src/components/SearchBarComponent/index.js
src/components/SearchBarComponent/styles.js

Implement a search bar component in the third theme. So that user can can search and filter items.
* Implement search bar component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/SearchBarComponent )
Resolves https://github.com/scorelab/Webiu/issues/303

implement search bar component

---

src/components/WelcomeContainer/WelcomeContainer.md
src/components/WelcomeContainer/WelcomeContainer.stories.js
src/components/WelcomeContainer/index.js
src/components/WelcomeContainer/styles.js
src/styles/theme.js

Implement a welcome container component in the third theme. So that user can see the welcome container in home page.
* Implement welcome container component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/WelcomeContainer )
Resolves https://github.com/scorelab/Webiu/issues/301

Implement welcome container component

---

src/components/Values/Values.md
src/components/Values/Values.stories.js
src/components/Values/index.js
src/components/Values/style.sass

Added Our Values Component for the Second Theme
Resolves #283

Added Our Values Component for the Second Theme

---

src/components/GradientBanner/GradientBanner.md
src/components/GradientBanner/GradientBanner.stories.js
src/components/GradientBanner/index.js
src/components/GradientBanner/style.sass

Added Gradient Banner Component for the Third Theme
Resolves #296
2. Mobile View

(chore) : Added Gradient Banner Component for the Third Theme

---

src/components/ModuleHeader/ModuleHeader.md
src/components/ModuleHeader/ModuleHeader.stories.js
src/components/ModuleHeader/index.js
src/components/ModuleHeader/styles.js

Implement a module header component in the third theme. So that header component will be displayed with basic information.
* Implement module header component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/ModuleHeader )
Resolves https://github.com/scorelab/Webiu/issues/311

implement module header

---

src/components/ImageCard/ImageCard.md
src/components/ImageCard/ImageCard.stories.js
src/components/ImageCard/index.js
src/components/ImageCard/styles.js

Implement a image card component in the third theme. So that we can display cards with image, title and button.
* Implement image card component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/ImageCard )
Resolves https://github.com/scorelab/Webiu/issues/313

implement imagecard component

---

src/components/NavBarThemeThree/NavBarThemeThree.md
src/components/NavBarThemeThree/NavBarThemeThree.stories.js
src/components/NavBarThemeThree/index.js
src/components/NavBarThemeThree/style.sass

Added NavBar Component for the Third Theme
Resolves #295 
2. Mobile View

(chore) : Added NavBar Component for the Third Theme

---

src/components/ContributeBanner/ContributeBanner.md
src/components/ContributeBanner/ContributeBanner.stories.js
src/components/ContributeBanner/index.js
src/components/ContributeBanner/style.sass

Added Contribute Banner Component for the Third Theme
Resolves #300 
2. Mobile View

(chore) : Added Contribute Banner Component for the Third Theme

---

src/components/VerticalStepper/VerticalStepper.md
src/components/VerticalStepper/VerticalStepper.stories.js
src/components/VerticalStepper/index.js
src/components/VerticalStepper/styles.js

Implement a vertical stepper component in the third theme. So that we can display steps clearly and more interactive way.
* Implement vertical stepper component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/VerticalStepper)
Resolves https://github.com/scorelab/Webiu/issues/324

implement vertical stepper component

---

package-lock.json
package.json
src/components/BarChart/BarChart.md
src/components/BarChart/BarChart.stories.js
src/components/BarChart/index.js

Implement a bar chart component in the third theme. So that we can display data in the chart with more analytic way.
* Implement BarChart component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/BarChart)
Resolves https://github.com/scorelab/Webiu/issues/326

Imlement BarChart Component

---

src/components/UserDetailForm/UserDetailForm.md
src/components/UserDetailForm/UserDetailForm.stories.js
src/components/UserDetailForm/index.js
src/components/UserDetailForm/styles.js

Implement a user detail component in the third theme. So that we can display user's basic information.
* Implement UserDetail component
* npm i
* npm run storybook (story will be displayed in LearningManagementSystem/UserDetail)
Resolves https://github.com/scorelab/Webiu/issues/329

Implement User Detail Form Component

---

src/components/FooterThemeThree/FooterThemeThree.md
src/components/FooterThemeThree/FooterThemeThree.stories.js
src/components/FooterThemeThree/index.js
src/components/FooterThemeThree/style.sass

Added Footer Component for the Third Theme
Resolves #299
2. Mobile View

(chore) : Added Footer Component for the Third Theme

---

src/components/DocsBanner/DocsBanner.md
src/components/DocsBanner/DocsBanner.stories.js
src/components/DocsBanner/index.js
src/components/DocsBanner/style.sass

Added DocsBanner Component for the Third Theme
Resolves #317 
2. Mobile View

(chore) : Added DocsBanner Component for the Third Theme

---

src/components/SideDrawerNavBar/SideDrawerNavBar.md
src/components/SideDrawerNavBar/SideDrawerNavBar.stories.js
src/components/SideDrawerNavBar/index.js
src/components/SideDrawerNavBar/styles.js

Implement a side drawer navigation bar in the fourth theme. So that user can navigate from this drawer and can hide the drawer if it is not necessary.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=1%3A4
* Implement side drawer navigation bar component
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/SideDrawerNavBar )
Resolves https://github.com/scorelab/Webiu/issues/336

Implement Side Drawer Navigation Bar

---

src/components/TextContainerWithBackgroundImage/TextContainerWithBackgroundImage.md
src/components/TextContainerWithBackgroundImage/TextContainerWithBackgroundImage.stories.js
src/components/TextContainerWithBackgroundImage/index.js
src/components/TextContainerWithBackgroundImage/styles.js

create a text container with background image in the fourth theme. So that user can see the text more clearly with the background image because of the overlay.
* Implement text container with background image component
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/TextContainerWithBackgroundImage )
Resolves https://github.com/scorelab/Webiu/issues/339

Imlement TextContainerWithBackgroundImage component

---

src/components/CommunityCards/CommunityCards.md
src/components/CommunityCards/CommunityCards.stories.js
src/components/CommunityCards/index.js
src/components/CommunityCards/style.sass

Added Community Card Component for the Third Theme
Resolves #321  

(chore) : Added Community Card Component for the Third Theme

---

src/components/BookingCard/BookingCard.md
src/components/BookingCard/BookingCard.stories.js
src/components/BookingCard/index.js
src/components/BookingCard/styles.js

Implement a booking card component in the fourth theme. So that user can see the available rooms, conditions and other details.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=95%3A364
* Implement booking card component
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/BookingCard )
Resolves https://github.com/scorelab/Webiu/issues/348

Implement BookingCard Component

---

package-lock.json
package.json
src/components/Ratings/Ratings.md
src/components/Ratings/Ratings.stories.js
src/components/Ratings/index.js
src/components/Ratings/styles.js

Implement a review & ratings component in the fourth theme. So that users reviews & ratings can be displayed in the website.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=95%3A364
* Implement ratings card component
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/RatingsCard )
Resolves https://github.com/scorelab/Webiu/issues/352

Implement Rating & Review Card

---

src/components/SignInWithSideImage/SignInWithSideImage.md
src/components/SignInWithSideImage/SignInWithSideImage.stories.js
src/components/SignInWithSideImage/index.js
src/components/SignInWithSideImage/styles.js

Implement a sign in component with side image in the fourth theme. So that users can sign in to the system through this page.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=95%3A364
* Implement signin component with side image
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/SignInWithSideImage )
Resolves https://github.com/scorelab/Webiu/issues/355

Implement signin component with side image

---

src/components/SignUpWithSideImage/SignUWithSideImage.md
src/components/SignUpWithSideImage/SignUpWithSideImage.stories.js
src/components/SignUpWithSideImage/index.js
src/components/SignUpWithSideImage/styles.js
src/styles/theme.js

Implement a signup component with side image in the fourth theme. So that users can sign up to the system through this page.
* Implement sign up component with side image
* npm i
* npm run storybook (story will be displayed in HotelManagementSystem/SignUpWithSideImage )
Resolves https://github.com/scorelab/Webiu/issues/357

Implement sign up component with side image

---

package-lock.json
package.json
src/components/AnimatedLogin/AnimatedLogin.md
src/components/AnimatedLogin/AnimatedLogin.stories.js
src/components/AnimatedLogin/index.js
src/components/AnimatedLogin/styles.js

Implement a login component with the animation and on top of the animated background with typewriter component in the fifth theme. So that users can see attractive login page.
* Implement login component with animated background and typewriter component
* npm i
* npm run storybook (story will be displayed in InventoryManagementSystem/AnimatedLogin )
Resolves https://github.com/scorelab/Webiu/issues/362

Implement animated login component

---

src/components/NavBarThemeFour/NavBarThemeFour.md
src/components/NavBarThemeFour/NavBarThemeFour.stories.js
src/components/NavBarThemeFour/index.js
src/components/NavBarThemeFour/style.sass

Added NavBar component of the fourth theme
Resolves #341
2. Mobile View

(chore): Added NavBar component of the fourth theme

---

src/components/MiniDrrawer/MiniDrawer.md
src/components/MiniDrrawer/MiniDrawer.stories.js
src/components/MiniDrrawer/index.js
src/components/MiniDrrawer/styles.js

Implement a mini drawer component in the fifth theme. So that users can navigate using this mini drawer.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=190%3A687
* Implement mini drawer component
* npm i
* npm run storybook (story will be displayed in InventoryManagementSystem/MiniDrawer )
Resolves https://github.com/scorelab/Webiu/issues/365

Implement Mini Drawer Component

---

src/components/Table/Table.md
src/components/Table/Table.stories.js
src/components/Table/index.js
src/components/Table/styles.js

Implement a Table component in the fifth theme. So that users can see their details in a tabular form.
Reference: https://www.figma.com/file/rX1jl4pa04VD9itnzneeih/Webiu?node-id=190%3A687.
* Implement table component
* npm i
* npm run storybook (story will be displayed in InventoryManagementSystem/Table )
Resolves https://github.com/scorelab/Webiu/issues/369

implement table component

---

src/components/NewsCard/NewsCard.md
src/components/NewsCard/NewsCard.stories.js
src/components/NewsCard/index.js
src/components/NewsCard/style.sass

Added News Card Component for the fourth theme
Resolves #350

(chore): Added News Card Component for the fourth theme

---

src/components/HeroSectionThemeThree/HeroSectionThemeThree.md
src/components/HeroSectionThemeThree/HeroSectionThemeThree.stories.js
src/components/HeroSectionThemeThree/index.js
src/components/HeroSectionThemeThree/style.sass

Added Hero Section Component for the Third theme
Resolves #305 

(chore): Added Hero Section Component for the Third theme

---

src/components/ServiceItemCard/ServiceItemCard.md
src/components/ServiceItemCard/ServiceItemCard.stories.js
src/components/ServiceItemCard/index.js
src/components/ServiceItemCard/style.sass

Added ServiceItemCard Component for the Fourth theme
Resolves #370

(chore): Added ServiceItemCard Component for the Fourth theme

---

src/components/ProjectDetailsCard/ProjectDetailCard.md
src/components/ProjectDetailsCard/ProjectDetailCard.stories.js
src/components/ProjectDetailsCard/index.js
src/components/ProjectDetailsCard/style.sass

Added ProjectDetailCard Component for the Fourth theme
Resolves #318 

(chore): Added ProjectDetailCard Component for the Fourth theme

---

src/components/CtaCard/CtaCard.md
src/components/CtaCard/CtaCard.stories.js
src/components/CtaCard/index.js
src/components/CtaCard/style.sass

Added Call to action card Component for the third theme
Resolves #322 

(chore): Added Call to action card Component for the third theme

---

src/components/ContactUsThemeFour/ContactUsThemeFour.md
src/components/ContactUsThemeFour/ContactUsThemeFour.stories.js
src/components/ContactUsThemeFour/index.js
src/components/ContactUsThemeFour/style.sass

Added Contact Us Component for the Fourth theme
Resolves #353 

(chore): Added Contact Us Component for the Fourth theme

---

src/components/MidSectionFour/MidSectionFour.md
src/components/MidSectionFour/MidSectionFour.stories.js
src/components/MidSectionFour/index.js
src/components/MidSectionFour/style.sass

Added mid-section Component for the Fourth theme
Resolves #385 

(chore): Added mid-section Component for the Fourth theme

---

src/components/InfoSection/InfoSection.md
src/components/InfoSection/InfoSection.stories.js
src/components/InfoSection/index.js
src/components/InfoSection/style.sass

Added Info Section Component for the Fourth theme
Resolves #351

(chore): Added Info Section Component for the Fourth theme

---

src/components/CardThemeFour/CardThemeFour.md
src/components/CardThemeFour/CardThemeFour.stories.js
src/components/CardThemeFour/index.js
src/components/CardThemeFour/style.sass

Added Individual Card Component for the Fourth theme
Resolves #387 

(chore): Added Individual Card Component for the Fourth theme

---

src/components/CardThemeFourGrid/CardThemeFourGrid.md
src/components/CardThemeFourGrid/CardThemeFourGrid.stories.js
src/components/CardThemeFourGrid/index.js
src/components/CardThemeFourGrid/style.sass

Added Card Grid Component for the Fourth theme
Resolves #387 

(chore): Added Card Grid Component for the Fourth theme

---

src/components/TestimonialAndFaq/TestimonialAndFaq.md
src/components/TestimonialAndFaq/TestimonialAndFaq.stories.js
src/components/TestimonialAndFaq/index.js
src/components/TestimonialAndFaq/style.sass

Added Testimonial and FAQ Component for the Fourth theme
Resolves #386  

(chore): Added Testimonial and FAQ Component for the Fourth theme

---

src/components/ServiceSection/ServiceSection.md
src/components/ServiceSection/ServiceSection.stories.js
src/components/ServiceSection/index.js
src/components/ServiceSection/style.sass

Added Service Section Component for the Fourth theme
Resolves #380  

(chore): Added Service Section Component for the Fourth theme

---

src/components/PopularProjectsCard/PopularProjectsCard.md
src/components/PopularProjectsCard/PopularProjectsCard.stories.js
src/components/PopularProjectsCard/index.js
src/components/PopularProjectsCard/style.sass

Added Popular Project Card Component for the Third theme
Resolves #319

(chore): Added Popular Project Card Component for the Third theme

---

src/components/NavBarThemeFive/NavBarThemeFive.stories.js
src/components/NavBarThemeFive/NavBarThemeFour.md
src/components/NavBarThemeFive/index.js
src/components/NavBarThemeFive/style.sass

Added Navbar Component for the Fifth theme
Resolves #397  

(chore): Added Navbar Component for the Fifth theme

---

src/components/ClickableInfo/ClickableInfoCard.md
src/components/ClickableInfo/ClickableInfoCard.stories.js
src/components/ClickableInfo/index.js
src/components/ClickableInfo/style.sass

Added Clickable Info Card Component for the third theme
Resolves #328 

(chore): Added Clickable Info Card Component for the third theme

---

src/components/ContactUsThemeFive/ContactUsThemeFive.stories.js
src/components/ContactUsThemeFive/ContactUsthemeFive.md
src/components/ContactUsThemeFive/index.js
src/components/ContactUsThemeFive/style.sass

Added Contact us for the fifth theme
Resolves #399 

(chore): Added Contact us for the fifth theme
